environment:
  matrix:
    # Disabling Py37 x64. Some weird problem with h5py. See github.com/tskit-dev/msprime/issues/678
    # - PYTHON: "C:\\Miniconda37-x64"
    - PYTHON: "C:\\Miniconda36-x64"

init:
  - cmd: ECHO Using %PYTHON%

install:
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - cmd: git submodule update --init --recursive
  # We have symlinks in the repo, which need to be treated specially on Windows.
  - cmd: git config core.symlinks true
  - cmd: git reset --hard
  - cmd: conda config --add channels conda-forge
  - cmd: conda install --yes --file=python\requirements\conda-minimal.txt
  - cmd: conda info -a

build_script:
  - cmd: cd python
  - cmd: python setup.py build_ext --inplace
  - cmd: pip install PyVCF
  - cmd: pip install newick
  - cmd: pip install python_jsonschema_objects
  - cmd: nosetests -vs

after_test:
  - cmd: python setup.py bdist_wheel
