environment:
  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
    - PYTHON: "C:\\Miniconda37-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

build: false

test_script:
  # We have symlinks in the repo, which need to be treated specially on Windows.
  - "git config core.symlinks true"
  - "git reset --hard"
  - "conda config --add channels conda-forge"
  - "conda create --yes --name testenv"
  - "activate testenv"
  - "conda install --yes --file=python/requirements/development.txt"
  - "cd python"
  - "python setup.py build_ext --inplace"
  - "nosetests -vs"

after_test:
  - "python setup.py bdist_wheel"
